---
title: "Gov 50 Final Project"
author: "Brennis Carrillo"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts ##

I am interested in exploring data related to...

* The economics of the Eras Concert
* The economics of the Marvel Cinematic Universe
* Public Opinion or voting patterns after Little Amal visits a city

## Proposal ##

For my final project, I want to study the question, Is the "The Walk" effective on positively influencing public opinion on refugees?
"The Walk" is an art project that created Little Amal, a 12-foot puppet that represents a 10-year old Syrian refugee girl, who visits cities  across the world to raise awareness about the ongoing refugee crisis. To start, I have pulled data from The Chicago Council on Global Affairs Poll: 2017 Biannual Survey which asks respondents "Do you support or oppose the United States […] Accepting Syrian refugees into the United States?" It is question Q267_1 in the data set and will work as a initial assessment of public opinion before Little Amal began her journey, I will continue to find more data, polled after Little Amal has visited a city. I hypothesize that public opinion will become more supportive. This would mean responses in support of accepting refugees in the United States would go up. If they remain stagnant or go down, it would prove, against my hypothesis, that “The Walk” is not effective. The explanatory variable of interest is whether or not Amal visited a city and the outcome variable is the difference in public opinion towards refugees.

## Data ##

```{r}
initial_assess <- read.csv("data/chicago_survey.csv")
```
